module.exports = {
    '/cs/': [
        'about',
        'bash',
        'bit_ops',
        'cheat_sheet',
        'cmake',
        'computer_composition',
        'concurrent_programming',
        'design_pattern',
        'gcc_toolchains',
        'git',
        'iptables',
        'keras',
        'knowledge_map',
        'logistic_regression',
        'lwip',
        'mbedtls',
        'python',
        'regular_expression',
        'risc-v',
        'scala',
        'think_in_code',
        'xtensa',
    ],
    '/ee/': [
        'about',
        'chisel',
        'control_system',
        'esp32',
        'infrared_remote',
        'motor_control',
        "openwrt",
        "usb",
    ],
    '/others/': [
        'about',
        'markdown',
        'oral_english',
        'terminal_presentation',
    ],
    '/': [
        ''
    ]
}
